# Dependencies
markdown:      kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Linbug
tagline:          'A blog about data science'
description:      'A blog about transitioning from life science to data science'
url:              http://linbug.github.io/
baseurl:          /linbug.github.io

author:
  name:           'Lin Taylor'
  url:            http://linbug.github.io/

paginate:         5

# Custom vars
          
avatar:           https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
github:           linbug

