# Dependencies
markdown:      kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Linbug
tagline:          'A blog about data science'
description:          'A blog about data science'
url:              http://linbug.github.io/
baseurl:          "/"

author:
  name:           'Lin Taylor'
  url:            http://linbug.github.io/

paginate:         5

# Custom vars
avatar:           https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
github:           linbug

gems: [jekyll-paginate]